version: "3.9"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest # Utilise l'image officielle de MongoDB
    restart: always
    volumes:
      - mongo_db:/data/db # Volume pour persister les données MongoDB

  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: api_db
      NAME: workshop_mds
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
